name: Sync Sedona Website

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sedona Website Branch to Specific Folder
        uses: actions/checkout@v2
        with:
          repository: apache/sedona
          path: sedona-source
          ref: website

      - name: Checkout Sedona Website ASF-Site Branch to Specific Folder
        uses: actions/checkout@v2
        with:
          repository: apache/sedona-website
          path: sedona-website
          ref: asf-site

      - name: Remove All Files from ASF-Site Branch
        run: |
          rm -rf sedona-website/*

      - name: Sync Content
        run: |
          cp -r sedona-source/* sedona-website/
          cd sedona-website
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Sync content from Sedona website branch" || echo "No changes to commit"

      - name: Push Changes
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cd sedona-website
          git config --unset-all http.https://github.com/.extraheader
          git remote set-url origin https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/apache/sedona-website.git
          git push origin asf-site